// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQ4NPv0F56sPlzMf4Y_73AIQgRYhRNl4',
    appId: '1:98603405648:web:f0ae7b036b09c80825dc55',
    messagingSenderId: '98603405648',
    projectId: 'iot-gas-leakage',
    authDomain: 'iot-gas-leakage.firebaseapp.com',
    storageBucket: 'iot-gas-leakage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9GQoOmkCTUrpgK_gRnSYLiEHBi97pyA',
    appId: '1:98603405648:android:b7717a5bf262f72825dc55',
    messagingSenderId: '98603405648',
    projectId: 'iot-gas-leakage',
    storageBucket: 'iot-gas-leakage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0Ts4qEHpwiDQi2_xoqVTxujFRBL3tAU',
    appId: '1:98603405648:ios:61470727eb68bbf425dc55',
    messagingSenderId: '98603405648',
    projectId: 'iot-gas-leakage',
    storageBucket: 'iot-gas-leakage.appspot.com',
    iosBundleId: 'com.example.gasLeakageDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK0Ts4qEHpwiDQi2_xoqVTxujFRBL3tAU',
    appId: '1:98603405648:ios:002c36a89449d7ff25dc55',
    messagingSenderId: '98603405648',
    projectId: 'iot-gas-leakage',
    storageBucket: 'iot-gas-leakage.appspot.com',
    iosBundleId: 'com.example.gasLeakageDetector.RunnerTests',
  );
}
