// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1HvOKGFcSYhIy1VvzC0X2Z3DBiS8KLk',
    appId: '1:680846974193:web:8ea586bbcd9fd9dfb65d50',
    messagingSenderId: '680846974193',
    projectId: 'gas-leakage-f87ff',
    authDomain: 'gas-leakage-f87ff.firebaseapp.com',
    storageBucket: 'gas-leakage-f87ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN0ud17qCu7pMA4QfiMo_p385uzXwPcyc',
    appId: '1:680846974193:android:365ee7563b3344d1b65d50',
    messagingSenderId: '680846974193',
    projectId: 'gas-leakage-f87ff',
    storageBucket: 'gas-leakage-f87ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_luE5xqNFa_KKBVUfXkUB2wRjmuHmkVs',
    appId: '1:680846974193:ios:876001b84d1e21acb65d50',
    messagingSenderId: '680846974193',
    projectId: 'gas-leakage-f87ff',
    storageBucket: 'gas-leakage-f87ff.appspot.com',
    iosBundleId: 'com.example.gasLeakageDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_luE5xqNFa_KKBVUfXkUB2wRjmuHmkVs',
    appId: '1:680846974193:ios:876001b84d1e21acb65d50',
    messagingSenderId: '680846974193',
    projectId: 'gas-leakage-f87ff',
    storageBucket: 'gas-leakage-f87ff.appspot.com',
    iosBundleId: 'com.example.gasLeakageDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF1HvOKGFcSYhIy1VvzC0X2Z3DBiS8KLk',
    appId: '1:680846974193:web:fe0a0dac452772f2b65d50',
    messagingSenderId: '680846974193',
    projectId: 'gas-leakage-f87ff',
    authDomain: 'gas-leakage-f87ff.firebaseapp.com',
    storageBucket: 'gas-leakage-f87ff.appspot.com',
  );

}